---
title: "Research"
bibliography: references.bib
csl: apa.csl
css: style.css
---
<!-- ### **Ongoing projects**  -->

<!-- As an organization established in 2025, we are currently in an early-stage research development phase.  -->
Our research projects (active and in-preparation) are currently in the domain of computational- and psycho-linguistics, neurodevelopmental disorders, and audiology.

### **Ongoing research projects**

Following projects are being initiated and conducted under NCCS:

1. **Predictive processing in typical and atypical population**
    - Area: Predictive language processing, Developmental stuttering
    - Status: Under IRB review
    - Methods: Lab-based behavioral experiment, Computational analysis
    - PI: Dr. Pratik Bhandari
<br> </br>

2. **Misophonia among Nepali adolescents**
    - Area: Sound sensitivity, Public health
    - Status: Under IRB review
    - Methods: Survey-based study
    - PI: Dr. Sajana Aryal
<br> </br>

3. **Hearing loss in Nepal**
    - Area: Audiology, Public health
    - Status: Ongoing
    - Methods: Meta-analysis
    - PI: Dr. Pratik Bhandari

[A paper](https://doi.org/10.1136/bmjopen-2025-109331) has recently been published in BMJ Open [@bhandari2026prevalence].

***

### Prior research by our members

Some of our researchers are also affiliated with universities and institutions around the world.
Below is the list of projects that they have undertaken across various domains of cognitive and related health sciences at different institutions prior to and alongside NCCS:

- **Advancing hearing health research in low- and middle-income countries**: @bhandari2026prevalence, @bhattarai2024qol, @raza2023review, @aryal2022nepali

- **Cognitive-communication & neurodegenerative conditions**: @bhattarai2021case

- **Understanding the mechanism behind sound sensitivity disorders**: @aryal2025emotion, @prabhu2025who, @aryal2024auditory, @aryal2023review

- **Aphasia & stroke-related communication disorders**: @bhattarai2026projected, @mohapatra2025prefrontal, @mohapatra2023recovery, @bhattarai2022lexical

- **Executive control in bilinguals**: @bhandari2020interlocutors, @mishra2019aging

- **Speech comprehension in adverse listening conditions**: @bhandari2022phd, @bhandari2024speechrate, @bhandari2022attention, @bhandari2021graded

- **Pediatric & special populations**: @fameen2022, @bhatarai2020

- **Telepractice & technology-based service delivery**: @mohapatra2023recovery, @bhattarai2022telepractice, @bhattarai2022challenges

- **Psychological response to covid-19 pandemic**: @lieberoth2021covid

- **Neurodiversity**: @bhandari2016autism

<!--**Extended high-frequency hearing and early cochlear dysfunction**: @aryal2026brainstem, @aryal2025probing, @aryal2025sharpness, @aryal2025review-->

<!-- **Misophonia among Nepali adolescents**: Data collection and analysis ongoing -->

<!--
##### **Cognitive consequences of multilingualism**

Knowing two or more languages is associated not only with social skills but is also shown to be beneficial for improved performance in cognitive and academic tasks among children. Nepali society is multicultural and multilingual, with 124 languages spoken as native languages (population census of 2021). What roles do such sociolinguistic and sociocultural diversities play in moderating the potentially beneficial effects of multilingualism? In this project, we aim to answer this question, primarily focusing on multilingual education in primary schools and its effects on academic performance and cognitive skills of high and low-proficiency L2 and L3 multilingual speakers.

Relevant works: @bhandari2020interlocutors, @mishra2019aging, @bhandari2018ms

##### **Many faces of autism care: Transition to adolescence and Stress on service providers**

Children diagnosed with autism face a complex set of challenges (social, biological, and emotional) as they transition to adolescence. It goes unaddressed in Nepal’s current healthcare framework. The policies and practices ignore the children’s unique set of needs. Healthcare professionals and policymakers alike have focused on promoting speech, language, and functional communication. There’s almost no attention to the changing needs of children transitioning to adolescence. At the same time, healthcare professionals are tasked with taking care of an overwhelming number of children suspected of autism. They are under immense stress and time pressure. They are also under-trained to take care of transitioning children, which worsens the condition. In this project, we objectively assess the factors that compromise the quality of care that autistic children receive. We also examine the factors that worsen the mental health (stress and emotional well-being) of autism care providers. We focus on children with autism transitioning to adolescence to find gaps in policy and practices that ought to be filled so that those children can receive better care in the days to come.-->

<!-- ### **Past projects**

NCCS researchers have led or been a part of studies across various domains of health and cognition. -->

<!--**Speech comprehension in adverse listening conditions**: @bhandari2024speechrate, @bhandari2022attention, @bhandari2021graded, @bhandari2022phd

**Psychological response to covid-19 pandemic**: @lieberoth2021covid

**Executive control in bilinguals**: @bhandari2020interlocutors, @mishra2019aging

**Neurodiversity**: @bhandari2016autism -->

<!-- ## **Culturally sensitive tool for autism diagnosis** -->
